### ISSUE TITLE
Strip front matter in Markdown preview

### ISSUE THREAD

**Issue by patrickderitter** [rusnasonov/vscode-hugo#1]
HI @rusnasonov, thanks for publishing this extension. If you're up for it, I have a feature request I would like to pitch with you. Would it be possible to use the Markdown preview function in VS Code with the frontmatter removed from the preview? A true Markdown preview would be very handy.

**Comment by rusnasonov** [comment]
Hi, thanks for an issue!

> Would it be possible to use the Markdown preview function in VS Code with the frontmatter removed from the preview?

I'm not sure about Markdown preview because Hugo add CSS classes and some HTML elements when rendering markdown (title, footer, header, etc).

I think is better to preview complete HTML for a post, maybe with [similar](https://github.com/HarshdeepGupta/live-html-preview) extension.

**Comment by patrickderitter** [comment]
Hi @rusnasonov, thanks for your reply.
My goals with this woud be to remove the front matter from the preview at first. Secondly, if the Markdown preview could actually render shortcodes (at least the defaults), that'd be great.
I think complete HTML preview could only be doable if `hugo server` would actually live render as you type, not on save.

**Comment by rusnasonov** [comment]
@patrickderitter you mean this [front matter](https://gohugo.io/content-management/front-matter/)? I don't see it on Markdown preview.
![demo](https://user-images.githubusercontent.com/4026379/43814898-0dee1e3c-9af7-11e8-8039-872d2c27b592.png)

**Comment by patrickderitter** [comment]
@rusnasonov I see it now. I was using TOML frontmatter, and with YAML frontmatter it won't show up in the preview. Thanks!
