### ISSUE TITLE
Add possibility to use parameter --kind in command new content

### ISSUE THREAD

**Issue by mckmonster** [rusnasonov/vscode-hugo#3]
Hello,

I think it should be cool to add the possibility to use that https://gohugo.io/content-management/archetypes/#directory-based-archetypes on functionnality create content.

In my case, I use the command `hugo new --kind balade-bundle balade/new-balade` by hand.

What do you think of that ?
thx

**Comment by rusnasonov** [comment]
Hi, cool feature!

Can you make this more general — create content from archetype files too, e.g. `hugo new -k my-type.md new-post/hello.md`? I check, option --kind works with archetypes files well.

**Comment by mckmonster** [comment]
Ok, I could try.
In fact, I didn't test if it's work with file or not.
I'll modify my code.

Le lun. 19 août 2019 à 18:05, Ruslan Nasonov <notifications@github.com> a
écrit :
